import {Dimensions, StyleSheet} from 'react-native';
import {colors} from '../../../core-constants';

export const Styles = StyleSheet.create({
  cardStyle: {
    alignItems: 'center',
    backgroundColor: colors.white,
    marginHorizontal: 20,
    borderRadius: 10,
  },
  padVert: {paddingVertical: 25},
  fontBold: {fontWeight: 'bold'},
  card1List: {flexDirection: 'row', marginVertical: 20},
  listView1: {
    borderRadius: 10,
    borderWidth: 0.5,
    padding: 2,
    borderColor: colors.textGray,
    marginHorizontal: 5,
  },
  textTitle: {
    backgroundColor: colors.gray,
    borderRadius: 10,
    paddingHorizontal: 5,
    fontWeight: 'bold',
  },
  greenLine: {
    backgroundColor: '#ECFFDC',
    flexDirection: 'row',
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    marginBottom: 15,
  },
  whiteWord: {
    backgroundColor: colors.white,
    borderColor: '#98FB98',
    borderWidth: 1,
    paddingHorizontal: 5,
    borderRadius: 10,
    marginRight: 10,
  },
  textGreen: {color: '#478778', fontWeight: 'semibold'},
  button1: {
    width: Dimensions.get('screen').width / 2.4,
    backgroundColor: colors.lightBlue,
    padding: 13,
    alignItems: 'center',
    borderRadius: 8,
    borderColor: colors.darkTextBlue,
    borderWidth: 0.5,
  },
  btnTitle1: {
    color: colors.darkBlue,
    fontWeight: 'bold',
    fontSize: 18,
  },
  button2: {
    width: Dimensions.get('screen').width / 2.4,
    backgroundColor: colors.lightPink,
    padding: 13,
    alignItems: 'center',
    borderRadius: 8,
    borderColor: colors.darkRed,
    borderWidth: 0.5,
  },
  buttonTitle2: {
    color: colors.darkRed,
    fontWeight: 'bold',
    fontSize: 18,
  },
  modalContainer: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: 420,
  },
  modalTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
  },
  modalBox: {
    borderColor: colors.gray,
    borderWidth: 0.6,
    borderRadius: 10,
    margin: 15,
    padding: 10,
  },
  priceTitle: {flexDirection: 'row', justifyContent: 'space-between'},
  alignRight: {textAlign: 'right'},
  modalSlider: {
    borderBottomWidth: 0.5,
    borderStyle: 'dashed',
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 10,
    marginBottom: 17,
  },
  minusBox: {
    backgroundColor: colors.gray,
    height: 25,
    width: 25,
    alignItems: 'center',
    marginTop: 7,
    borderRadius: 8,
  },
  sliderView: {flex: 1, marginHorizontal: 15},
  trackStyle: {height: 10, borderRadius: 10},
  plusBox: {
    backgroundColor: colors.gray,
    height: 25,
    width: 25,
    alignItems: 'center',
    marginTop: 7,
    borderRadius: 8,
  },
  amountBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
  },
  amountValue: {textAlign: 'center', fontWeight: 'bold'},
  rightAmountValue: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'green',
  },
  swipeView: {paddingHorizontal: 15, alignItems: 'center'},
  balanceView: {alignItems: 'center', paddingTop: 10},
  buttonView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
    backgroundColor: colors.white,
    marginHorizontal: 10,
    marginVertical: 15,
    padding: 10,
    borderRadius: 8,
    borderWidth: 0.3,
  },
});
