import {Dimensions, StyleSheet} from 'react-native';
import {colors} from '../../../core-constants';

export const Styles = StyleSheet.create({
  mainView: {backgroundColor: 'lightGray', flex: 1, paddingTop: 10},
  searchShadow: {
    margin: 10,
    marginTop: 20,
    marginHorizontal: 15,
    backgroundColor: 'white',
    borderRadius: 25,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 14,
  },
  container: {paddingLeft: 10},
  flatContainer: {alignSelf: 'flex-start'},
  touchable: {
    padding: 10,
    borderRadius: 10,
    marginVertical: 5,
    marginRight: 7,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
  },
  title: {color: colors.black, alignSelf: 'center', fontWeight: 'bold'},
  iconView: {justifyContent: 'center', marginRight: 8},
  inputView: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginVertical: 6,
  },
  justCenter: {justifyContent: 'center'},
  imageView: {width: 26, height: 20},
  titleText: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.black,
    marginLeft: 10,
    maxWidth: '90%',
  },
  title2: {color: colors.black, marginTop: 5, fontWeight: 'bold'},
  subTitle: {
    color: colors.black,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 18,
    fontSize: 12,
  },
  listIcon: {
    justifyContent: 'center',
    marginBottom: 15,
  },
  headerView: {
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  horizontalImage: {
    marginHorizontal: 10,
    marginTop: 10,
    marginBottom: 15,
  },
  imageStyle: {height: 120, width: Dimensions.get('screen').width - 20},
  flatList: {alignSelf: 'flex-start', marginLeft: 10},
  touchableList: {
    padding: 10,
    borderRadius: 10,
    marginVertical: 5,
    marginRight: 7,
    backgroundColor: colors.white,
  },
  alignCenter: {alignItems: 'center'},
  trending: {
    marginLeft: 10,
    marginTop: 20,
    marginBottom: 5,
    fontWeight: 'bold',
  },
  matchListView: {marginTop: 10, paddingBottom: 10},
  matchTouch: {
    backgroundColor: 'white',
    marginHorizontal: 10,
    marginVertical: 8,
    padding: 10,
    borderRadius: 8,
    paddingHorizontal: 15,
  },
  matchListViewAlign: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  matchTextTitle: {
    color: colors.black,
    alignSelf: 'center',
    fontWeight: 'bold',
    marginTop: 5,
    fontSize: 17,
    textAlign: 'center',
  },
  buttonView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  button1: {
    width: Dimensions.get('screen').width / 2.4,
    backgroundColor: colors.lightBlue,
    padding: 13,
    alignItems: 'center',
    borderRadius: 8,
    borderColor: colors.darkTextBlue,
    borderWidth: 0.5,
  },
  btnTitle1: {
    color: colors.darkBlue,
    fontWeight: 'bold',
    fontSize: 18,
  },
  button2: {
    width: Dimensions.get('screen').width / 2.4,
    backgroundColor: colors.lightPink,
    padding: 13,
    alignItems: 'center',
    borderRadius: 8,
    borderColor: colors.darkRed,
    borderWidth: 0.5,
  },
  buttonTitle2: {
    color: colors.darkRed,
    fontWeight: 'bold',
    fontSize: 18,
  },
});
